# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'

# Website info
name: 'Tirana Code_'
description: "Blog."

# Author's info
author: 'Aldo'
# edit 'categories' in the front matter of every post to match this username
username: aldo
bio: 'Thelle, thelle, njeri i mire...'
location: 'Edinburg, Skoci'
url: 'https://www.linkedin.com/in/arjaldokaraj'
image: 'assets/images/aldo.jpg'

short_url: 'linkedin.com/in/arjaldokaraj'
google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /blog/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
